export const MenuData=[
    {
        id:1,
        title:"Home",
        url:"/"
    },
    {
        id:2,
        title:"Shop",
        url:"/shop"
    },
    {
        id:"3",
        title:"About",
        url:"/about"
    },
    {
        id:"4",
        title:"Contact",
        url:"/contact"
    },
    {
        id:"5",
        title:"Faqs",
        url:"/faqs"
    },
    {
        id:"6",
        title:"Shipping",
        url:"/policies/shipping-policy"
    }
]